### ISSUE TITLE
Deprecated Functionality: json_decode(): Passing null to parameter #1

### ISSUE THREAD

**Issue by ivangraybox** [rejoiner/magento2-plugin#10]
`Noticed exception 'Exception' with message 'Deprecated Functionality: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in /var/www/magento2/vendor/rejoiner/module-acr/Observer/ControllerActionPredispatch.php on line 44' in /var/www/magento2/vendor/magento/framework/App/ErrorHandler.php:61`

**Comment by saschabratton** [comment]
@ivangraybox Latest version 2.5.6 with this fix is published and available via composer.

**Comment by ivangraybox** [comment]
@saschabratton, thanks for fixing this and other issues promptly. I'll let you know if you I see anything else.sda
