### ISSUE TITLE
getLabel() is undefined

### ISSUE THREAD

**Issue by bartdominiak** [rejoiner/magento2-plugin#2]
Quest checkout form:
<img width="863" alt="Zrzut ekranu 2019-07-13 o 23 16 53" src="https://user-images.githubusercontent.com/18058305/61176627-6351f780-a5c4-11e9-9b9d-9aecb6b56eff.png">

This error is connected to this knockout template:
https://github.com/rejoiner/magento2-plugin/blob/defdb3254d795ebf6999a4c5aedb966c9a29113a/view/frontend/web/template/checkout/view/subscription_guest.html#L7-L10

This should be wrapped in an condition, and prevent undefined variables binding inside template.
```html
<!-- ko if: showSubscriptionGuest -->
  ...
<!-- /ko -->

**Comment by saschabratton** [comment]
Thanks @bartdominiak we will take a look at implementing your fix for this issue.

**Comment by pavlots** [comment]
The issue has beeb fixed.
