### ISSUE TITLE
Deprecated Functionality: Function strftime() is deprecated

### ISSUE THREAD

**Issue by ivangraybox** [rejoiner/magento2-plugin#8]
Error `Deprecated Functionality: Function strftime() is deprecated in /var/www/html/vendor/rejoiner/module-acr/Observer/CheckoutOnepageControllerSuccessAction.php on line 56` on checkout success page. The same function is also used in `Rejoiner\Acr\Cron\TrackOrderSuccessConversion`.

**Comment by ivangraybox** [comment]
@saschabratton, any ETA on getting this issue fixed?

**Comment by saschabratton** [comment]
> @saschabratton, any ETA on getting this issue fixed?

Yes, I believe we can replace this with just `date()` function. I'll follow up later today or tomorrow.

**Comment by saschabratton** [comment]
@ivangraybox Please take a look at 2.5.5 branch: 68085d8f13538160d7a700efc9a0260ad08e537f

Let me know if this resolves your issue and I'll publish to composer. Thanks!
